### ISSUE TITLE
上下线的一点问题

### ISSUE THREAD

**Issue by congleetea** [redink/emqtt_dev#1]
你好, 目前使用connected和disconnected的hook来判断上下线在下面这种情况下, 下线就不准了:
我测试了在出现异常之后, client断开连接时是不执行disconnected的hook的, 这样离线信息似乎就不准了. 
这种情况下如何能准确的判断在线和离线呢?  
 能不能指导一下.  最近在判断在线离线的时候老是出现问题.  谢谢

**Comment by redink** [comment]
```
在出现异常之后, client断开连接时是不执行disconnected的hook的
```
举个例子?

**Comment by congleetea** [comment]
比如我使用 http://www.hivemq.com/demos/websocket-client/ 这个发布qos=2的消息时, 就会断开连接, 这时候disconnected的hook没有被执行.

**Comment by redink** [comment]
1. 我不确定通过你的url 发送ws qos2 的消息,会不会指定`mqtt_packet_id`,如果是undefined的话,emqttd 确实会出现问题
2. 但是不论是否会出现问题,我在我本地电脑模拟发送ws 消息, 使emqttd 出现异常, sub_connection 收到disconnected 的消息, 如下:
```
Message from $SYS/brokers/emqttd@127.0.0.1/clients/C_1463762435838/disconnected: <<"{\"clientid\":\"C_1463762435838\",\"reason\":\"badarg\",\"ts\":1463762447}
```
注意消息中的 `badarg`.

**Comment by congleetea** [comment]
我是用的这个ws mqtt client 库确实是有点问题.  我用他发布qos=2消息时确实没有执行disconnected的hook, 你有没有什么好的库推荐一下

**Comment by redink** [comment]
client 这块了解的很少，这个确实无能为力了。

**Comment by congleetea** [comment]
好的 ,   非常感谢你.

**Comment by redink** [comment]
那我先把这个issue 关了？
